export default function CasesPage() {
      return (
          <main
                style={{
                        minHeight: "100vh",
                                background: "#F7F5F0",
                                        color: "#17233D",
                                                padding: "20px",
                                                        fontFamily: "Arial, sans-serif",
                                                              }}
                                                                  >
                                                                        <h1>Customer Cases</h1>

                                                                              <p style={{ color: "#5B6472" }}>
                                                                                      Track and manage every customer issue from open to resolved.
                                                                                            </p>

                                                                                                  <div
                                                                                                          style={{
                                                                                                                    background: "#17233D",
                                                                                                                              color: "#FFFFFF",
                                                                                                                                        padding: "20px",
                                                                                                                                                  borderRadius: "16px",
                                                                                                                                                            marginTop: "24px",
                                                                                                                                                                    }}
                                                                                                                                                                          >
                                                                                                                                                                                  <p style={{ color: "#F2994A", marginTop: 0 }}>
                                                                                                                                                                                            CASE OVERVIEW
                                                                                                                                                                                                    </p>

                                                                                                                                                                                                            <h2 style={{ marginBottom: 0 }}>12 active cases</h2>
                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                        <h2 style={{ marginTop: "32px" }}>Active cases</h2>

                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                background: "#FFFFFF",
                                                                                                                                                                                                                                                          padding: "18px",
                                                                                                                                                                                                                                                                    borderRadius: "14px",
                                                                                                                                                                                                                                                                              border: "1px solid #E4E1D8",
                                                                                                                                                                                                                                                                                        marginBottom: "12px",
                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                              <strong>ARQ-1042 · Delayed Delivery</strong>
                                                                                                                                                                                                                                                                                                                      <p style={{ color: "#5B6472" }}>
                                                                                                                                                                                                                                                                                                                                Customer: Sarah · Waiting for an update
                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                <span style={{ color: "#F2994A" }}>Needs attention</span>
                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                            <div
                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                              background: "#FFFFFF",
                                                                                                                                                                                                                                                                                                                                                                                        padding: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                            border: "1px solid #E4E1D8",
                                                                                                                                                                                                                                                                                                                                                                                                                      marginBottom: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                            <strong>ARQ-1038 · Account Update</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style={{ color: "#5B6472" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              Customer: Michael · Follow-up scheduled today
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span style={{ color: "#2C4570" }}>In progress</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: "#FFFFFF",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: "1px solid #E4E1D8",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <strong>ARQ-1031 · Billing Question</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p style={{ color: "#5B6472" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Customer: Ada · Awaiting team response
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span style={{ color: "#2C4570" }}>Open</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
