import Link from "next/link";
import PriorityBadge from "@/components/PriorityBadge";
import { tickets } from "@/lib/tickets";

export default async function TicketDetailsPage({
  params,
  }: {
    params: Promise<{ id: string }>;
    }) {
      const { id } = await params;

        const ticket = tickets.find(
            (item) => item.id === id
              );

                if (!ticket) {
                    return (
                          <main style={{ padding: "28px" }}>
                                  <h1>Ticket not found</h1>
                                          <Link href="/Tickets">
                                                    ← Back to Tickets
                                                            </Link>
                                                                  </main>
                                                                      );
                                                                        }

                                                                          return (
                                                                              <main
                                                                                    style={{
                                                                                            minHeight: "100vh",
                                                                                                    background: "#F7F5F0",
                                                                                                            color: "#17233D",
                                                                                                                    padding: "28px",
                                                                                                                            fontFamily: "Arial, sans-serif",
                                                                                                                                  }}
                                                                                                                                      >
                                                                                                                                            <Link
                                                                                                                                                    href="/Tickets"
                                                                                                                                                            style={{ color: "#F2994A" }}
                                                                                                                                                                  >
                                                                                                                                                                          ← Back to Tickets
                                                                                                                                                                                </Link>

                                                                                                                                                                                      <p style={{ color: "#F2994A" }}>
                                                                                                                                                                                              TICKET {ticket.id}
                                                                                                                                                                                                    </p>

                                                                                                                                                                                                          <h1>{ticket.subject}</h1>

                                                                                                                                                                                                                <PriorityBadge
                                                                                                                                                                                                                        priority={ticket.priority}
                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                    <p
                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                      color: ticket.statusColor,
                                                                                                                                                                                                                                                                fontWeight: "bold",
                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                      ● {ticket.status}
                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                  <section
                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                    background: "#FFFFFF",
                                                                                                                                                                                                                                                                                                                              padding: "20px",
                                                                                                                                                                                                                                                                                                                                        borderRadius: "12px",
                                                                                                                                                                                                                                                                                                                                                  marginTop: "24px",
                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                        <h2>Conversation</h2>

                                                                                                                                                                                                                                                                                                                                                                                {ticket.activities.map(
                                                                                                                                                                                                                                                                                                                                                                                          (activity, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                      <div key={index}>
                                                                                                                                                                                                                                                                                                                                                                                                                    <strong>{activity.person}</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <small> · {activity.time}</small>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>{activity.text}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <hr />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <section
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          background: "#FFFFFF",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2>Ticket Details</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>Customer: {ticket.customer}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>Email: {ticket.email}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>Category: {ticket.category}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>Agent: {ticket.agent}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>Team: {ticket.team}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }